#!/bin/bash

cd `dirname $0`

DATE=`date +%Y-%m-%d`
RECIP="Your.Email@example.com"
SUBJECT="Automatic tls-checker results from $HOSTNAME $DATE"

OUTDIR=$(./uvt-tls)

if [ -d "${OUTDIR}" ] ; then
	cat "${OUTDIR}/body" | mutt -s "$SUBJECT" "$RECIP" -a "${OUTDIR}"/*.txt
else
	echo Cannot find output directory: "'${OUTDIR}'"
fi
